---
system_packages:
  - bc
  - ca-certificates
  - curl
  - git
  - gnu-free-mono-fonts
  - gnu-free-sans-fonts
  - gnu-free-serif-fonts
  - gnuplot
  - epel-release
  - mc
  - ntp
  - net-tools
  - psmisc
  - screen
  - tree
  - unzip
  - vim
  - wget
  - zip